### ISSUE TITLE
unable to install pylibra

### ISSUE THREAD

**Issue by trinayanbhatt** [bandprotocol/pylibra#15]
Run through this error while installing pylibra.

Collecting black==19.3b0 (from pylibra)
  Using cached https://files.pythonhosted.org/packages/89/07/aebb10fb8f2ffbac672dfbebffa724643bc84cf012a57737a622d1dabddb/black-19.3b0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cjHnxL/black/setup.py", line 13
        def get_long_description() -> str:
                                   ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cjHnxL/black/

**Comment by saguywalker** [comment]
Which version of python are you using?

**Comment by suraneti** [comment]
@trinayanbhatt Python2 is not compatible with this library.

**Comment by trinayanbhatt** [comment]
@saguywalker I have tried with python3 both with Python 3.5.2 and with Python 3.7.

**Comment by trinayanbhatt** [comment]
@suraneti Yes I am trying with python3 only.

**Comment by saguywalker** [comment]
According to https://github.com/psf/black/issues/439#issuecomment-514227490, you should try to run `pip install --pre black` with Python 3.7.
